source 'http://rubygems.org'

gem 'rails', '3.0.3'
gem 'sqlite3-ruby', :require => 'sqlite3'
gem 'devise'
gem 'omniauth'


group :development, :test do
  gem 'webrat'
  gem 'rspec-rails'
  gem 'annotate'
  gem 'cucumber-rails'
 
end
