require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe ProductsController do
  describe "The truth" do
    it "should be True" do
      "to".should == "t"
    end
  end


end
